In [ ]:
import pandas as pd

In [ ]:
url = 'https://drive.google.com/file/d/1f90skYv9mocmj5D0SQODXDBbMF3vl4Us/view?usp=sharing'
path = 'https://drive.google.com/uc?export=download&id='+url.split('/')[-2]
discounts_df = pd.read_csv(path)
discounts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53231 entries, 0 to 53230
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_order          53231 non-null  int64
 1   product_quantity  53231 non-null  int64
 2   sku               53231 non-null  object
 3   unit_price        53231 non-null  float64
 4   date              53231 non-null  object
 5   name              53231 non-null  object
 6   desc              53231 non-null  object
 7   price             53231 non-null  float64
 8   type              53220 non-null  object
 9   discount          53231 non-null  float64
dtypes: float64(3), int64(2), object(5)
memory usage: 4.1+ MB

In [ ]:
discounts_df.head()

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount
0,299545,1,OWC0100,47.49,2017-01-01 01:46:16,OWC In-line Digital Temperature Sensor Kit HDD...,Kit temperature sensor for HDD iMac 21 inch an...,60.99,12755395,13.50
1,299546,1,IOT0014,18.99,2017-01-01 01:50:34,iOttie Easy View 2 Car Black Support,IPhone car holder 7 plus / 7/6 Plus / 6 / 5s /...,22.95,5720,3.96
2,295347,1,APP0700,72.19,2017-01-01 01:54:11,Apple 85W MagSafe 2 charger MacBook Pro screen...,Apple MagSafe 2 Charger for MacBook Pro 15-inc...,89.00,13005399,16.81
3,299556,1,CRU0039-A,60.90,2017-01-01 02:20:14,(Open) Crucial 240GB SSD 7mm BX200,SSD hard drive and high-speed performance with...,76.99,1298,16.09
4,299561,1,PEB0015,142.49,2017-01-01 02:38:50,Pebble Smartwatch Time Steel Black,Bluetooth Smart Watch with steel case leather ...,299.99,11905404,157.50

In [ ]:
discounts_df['type'] = pd.to_numeric(discounts_df['type'], errors='coerce').astype('Int64')

In [ ]:
discounts_df['discount'].sum()

np.float64(1390216.63)

In [ ]:
# count unique values in type column
discounts_df['type'].value_counts()
list_types = discounts_df['type'].value_counts()
list_types

11865403     4374
11935397     3872
11905404     3145
1364         3136
5384         2319
             ...
5406            2
11434           2
113271716       2
21622158        1
113464259       1
Name: type, Length: 106, dtype: Int64

In [ ]:
len(list_types)

106

In [ ]:
type(list_types)
# list_types

pandas.core.series.Series

In [ ]:
# Get first occurrence index of each unique value in "type" column
first_indices = discounts_df.drop_duplicates(subset="type", keep="first").index
first_indices

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            17322, 19390, 23072, 23097, 23858, 29888, 33494, 38037, 47281,
            48804],
           dtype='int64', length=107)

In [ ]:
# show the rows with the first occurrence of each unique value in "type" column
selected = discounts_df.loc[first_indices, ['name', 'type']].head(200)
pd.set_option("display.max_rows", 200)  # Show all rows
selected
len(selected)

107

In [ ]:
# create product category column
discounts_df['product_category'] = ""
discounts_df

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount,product_category
0,299545,1,OWC0100,47.49,2017-01-01 01:46:16,OWC In-line Digital Temperature Sensor Kit HDD...,Kit temperature sensor for HDD iMac 21 inch an...,60.99,12755395,13.50,
1,299546,1,IOT0014,18.99,2017-01-01 01:50:34,iOttie Easy View 2 Car Black Support,IPhone car holder 7 plus / 7/6 Plus / 6 / 5s /...,22.95,5720,3.96,
2,295347,1,APP0700,72.19,2017-01-01 01:54:11,Apple 85W MagSafe 2 charger MacBook Pro screen...,Apple MagSafe 2 Charger for MacBook Pro 15-inc...,89.00,13005399,16.81,
3,299556,1,CRU0039-A,60.90,2017-01-01 02:20:14,(Open) Crucial 240GB SSD 7mm BX200,SSD hard drive and high-speed performance with...,76.99,1298,16.09,
4,299561,1,PEB0015,142.49,2017-01-01 02:38:50,Pebble Smartwatch Time Steel Black,Bluetooth Smart Watch with steel case leather ...,299.99,11905404,157.50,
...,...,...,...,...,...,...,...,...,...,...,...
53226,527035,1,APP0698,9.99,2018-03-14 11:42:41,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,
53227,527070,2,APP0698,9.99,2018-03-14 11:49:01,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,
53228,527074,2,APP0698,9.99,2018-03-14 11:49:36,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,
53229,527096,3,APP0698,9.99,2018-03-14 11:54:35,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,
53230,527112,1,APP0698,9.99,2018-03-14 11:58:13,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,

In [ ]:
# show the first 10 rows based on the type column
res = discounts_df.loc[discounts_df['type'] == 1714].head(10)
res

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount,product_category
9051,345406,1,APP1976,399.0,2017-04-11 14:35:07,Apple iPad Wi-Fi 32GB Gold,New iPad Wi-Fi 32GB Gold (MPGT2TY / A),402.81,1714,3.81,
9389,346822,1,APP1978,383.0,2017-04-17 22:10:07,Apple iPad Wi-Fi 32GB Space Gray,New iPad Wi-Fi 32GB Space Gray (MP2F2TY / A),402.81,1714,19.81,
9410,346897,1,APP1978,383.0,2017-04-18 04:47:22,Apple iPad Wi-Fi 32GB Space Gray,New iPad Wi-Fi 32GB Space Gray (MP2F2TY / A),402.81,1714,19.81,
9411,346898,1,APP1979,479.0,2017-04-18 05:07:42,Apple iPad Wi-Fi 128GB Space Gray,New Apple iPad Wi-Fi 128GB Space Gray (MP2H2TY...,502.81,1714,23.81,
9432,346955,1,APP1975,479.0,2017-04-18 10:16:41,Apple iPad Wi-Fi 128GB Silver,New iPad Wi-Fi 128GB Silver (MP2J2TY / A),502.81,1714,23.81,
9476,347034,1,APP1979,479.0,2017-04-18 12:59:23,Apple iPad Wi-Fi 128GB Space Gray,New Apple iPad Wi-Fi 128GB Space Gray (MP2H2TY...,502.81,1714,23.81,
9510,347163,1,APP1978,383.0,2017-04-18 18:34:52,Apple iPad Wi-Fi 32GB Space Gray,New iPad Wi-Fi 32GB Space Gray (MP2F2TY / A),402.81,1714,19.81,
9519,347186,1,APP1978,383.0,2017-04-18 19:48:12,Apple iPad Wi-Fi 32GB Space Gray,New iPad Wi-Fi 32GB Space Gray (MP2F2TY / A),402.81,1714,19.81,
9526,347235,1,APP1977,479.0,2017-04-18 23:08:22,Apple iPad Wi-Fi 128GB Gold,New iPad Wi-Fi 128GB Gold (MPGW2TY / A),502.81,1714,23.81,
9547,347309,3,APP1978,383.0,2017-04-19 10:00:25,Apple iPad Wi-Fi 32GB Space Gray,New iPad Wi-Fi 32GB Space Gray (MP2F2TY / A),402.81,1714,19.81,

In [ ]:
# group by type and sku and count the number of rows for each type
discounts_df.groupby("type").count().nlargest(50, "sku")

,id_order,product_quantity,sku,unit_price,date,name,desc,price,discount,product_category
type,,,,,,,,,,
11865403,4374,4374,4374,4374,4374,4374,4374,4374,4374,4374
11935397,3872,3872,3872,3872,3872,3872,3872,3872,3872,3872
11905404,3145,3145,3145,3145,3145,3145,3145,3145,3145,3145
1364,3136,3136,3136,3136,3136,3136,3136,3136,3136,3136
5384,2319,2319,2319,2319,2319,2319,2319,2319,2319,2319
12215397,1982,1982,1982,1982,1982,1982,1982,1982,1982,1982
12655397,1832,1832,1832,1832,1832,1832,1832,1832,1832,1832
12585395,1815,1815,1815,1815,1815,1815,1815,1815,1815,1815
1296,1489,1489,1489,1489,1489,1489,1489,1489,1489,1489
1230,1409,1409,1409,1409,1409,1409,1409,1409,1409,1409
1405,1182,1182,1182,1182,1182,1182,1182,1182,1182,1182
1231,1123,1123,1123,1123,1123,1123,1123,1123,1123,1123
12175397,1093,1093,1093,1093,1093,1093,1093,1093,1093,1093
1325,1069,1069,1069,1069,1069,1069,1069,1069,1069,1069
13835403,971,971,971,971,971,971,971,971,971,971
42945397,860,860,860,860,860,860,860,860,860,860
12755395,854,854,854,854,854,854,854,854,854,854
13555403,822,822,822,822,822,822,822,822,822,822
13615399,821,821,821,821,821,821,821,821,821,821
13855401,818,818,818,818,818,818,818,818,818,818
10142,802,802,802,802,802,802,802,802,802,802
51601716,796,796,796,796,796,796,796,796,796,796
5398,785,785,785,785,785,785,785,785,785,785
12635403,713,713,713,713,713,713,713,713,713,713
1433,707,707,707,707,707,707,707,707,707,707
1229,684,684,684,684,684,684,684,684,684,684
14305406,683,683,683,683,683,683,683,683,683,683
12995397,670,670,670,670,670,670,670,670,670,670
13005399,669,669,669,669,669,669,669,669,669,669
1298,568,568,568,568,568,568,568,568,568,568
12645406,566,566,566,566,566,566,566,566,566,566
57445397,556,556,556,556,556,556,556,556,556,556
12575403,531,531,531,531,531,531,531,531,531,531
1515,527,527,527,527,527,527,527,527,527,527
1387,520,520,520,520,520,520,520,520,520,520
5395,491,491,491,491,491,491,491,491,491,491
8696,434,434,434,434,434,434,434,434,434,434
1334,429,429,429,429,429,429,429,429,429,429
1392,426,426,426,426,426,426,426,426,426,426
24895185,386,386,386,386,386,386,386,386,386,386
21561716,334,334,334,334,334,334,334,334,334,334
21485407,317,317,317,317,317,317,317,317,317,317
85641716,300,300,300,300,300,300,300,300,300,300
2449,276,276,276,276,276,276,276,276,276,276
113291716,274,274,274,274,274,274,274,274,274,274
24215399,264,264,264,264,264,264,264,264,264,264
1714,256,256,256,256,256,256,256,256,256,256
14365395,241,241,241,241,241,241,241,241,241,241
5720,235,235,235,235,235,235,235,235,235,235
5399,219,219,219,219,219,219,219,219,219,219

In [ ]:
for n in range(20,71):
  print(f"With the {n} largest types, we account for {((discounts_df.groupby('type').count().nlargest(n, 'sku')['sku'].sum()) / (discounts_df.shape[0]) * 100).round(2)}% of all products.")

With the 20 largest types, we account for 65.72% of all products.
With the 21 largest types, we account for 67.23% of all products.
With the 22 largest types, we account for 68.73% of all products.
With the 23 largest types, we account for 70.2% of all products.
With the 24 largest types, we account for 71.54% of all products.
With the 25 largest types, we account for 72.87% of all products.
With the 26 largest types, we account for 74.15% of all products.
With the 27 largest types, we account for 75.44% of all products.
With the 28 largest types, we account for 76.7% of all products.
With the 29 largest types, we account for 77.95% of all products.
With the 30 largest types, we account for 79.02% of all products.
With the 31 largest types, we account for 80.08% of all products.
With the 32 largest types, we account for 81.13% of all products.
With the 33 largest types, we account for 82.13% of all products.
With the 34 largest types, we account for 83.12% of all products.
With the 35 largest types, we account for 84.09% of all products.
With the 36 largest types, we account for 85.01% of all products.
With the 37 largest types, we account for 85.83% of all products.
With the 38 largest types, we account for 86.64% of all products.
With the 39 largest types, we account for 87.44% of all products.
With the 40 largest types, we account for 88.16% of all products.
With the 41 largest types, we account for 88.79% of all products.
With the 42 largest types, we account for 89.38% of all products.
With the 43 largest types, we account for 89.95% of all products.
With the 44 largest types, we account for 90.47% of all products.
With the 45 largest types, we account for 90.98% of all products.
With the 46 largest types, we account for 91.48% of all products.
With the 47 largest types, we account for 91.96% of all products.
With the 48 largest types, we account for 92.41% of all products.
With the 49 largest types, we account for 92.85% of all products.
With the 50 largest types, we account for 93.26% of all products.
With the 51 largest types, we account for 93.67% of all products.
With the 52 largest types, we account for 94.05% of all products.
With the 53 largest types, we account for 94.42% of all products.
With the 54 largest types, we account for 94.76% of all products.
With the 55 largest types, we account for 95.1% of all products.
With the 56 largest types, we account for 95.41% of all products.
With the 57 largest types, we account for 95.71% of all products.
With the 58 largest types, we account for 96.01% of all products.
With the 59 largest types, we account for 96.3% of all products.
With the 60 largest types, we account for 96.52% of all products.
With the 61 largest types, we account for 96.72% of all products.
With the 62 largest types, we account for 96.92% of all products.
With the 63 largest types, we account for 97.11% of all products.
With the 64 largest types, we account for 97.3% of all products.
With the 65 largest types, we account for 97.47% of all products.
With the 66 largest types, we account for 97.62% of all products.
With the 67 largest types, we account for 97.77% of all products.
With the 68 largest types, we account for 97.9% of all products.
With the 69 largest types, we account for 98.01% of all products.
With the 70 largest types, we account for 98.12% of all products.

In [ ]:
discounts_df.loc[discounts_df['type'] == 51871714].sample(10)

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount,product_category
43375,483882,1,APP1489,599.00,2018-01-06 19:16:40,"Apple iPad Pro 9.7 ""128GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 128GB Wi-Fi Gray Space.,789.0,51871714,190.00,
8192,326121,1,APP1489,757.99,2017-02-19 00:02:48,"Apple iPad Pro 9.7 ""128GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 128GB Wi-Fi Gray Space.,789.0,51871714,31.01,
44846,490360,1,APP1489,599.00,2018-01-14 01:02:22,"Apple iPad Pro 9.7 ""128GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 128GB Wi-Fi Gray Space.,789.0,51871714,190.00,
767,302013,1,APP1501,939.00,2017-01-03 20:48:27,"Apple iPad Pro 9.7 ""Wi-Fi + Cellular 128GB Spa...",9.7-inch Apple iPad Pro Wi-Fi + Cellular 128GB...,939.0,51871714,0.00,
46247,496703,1,APP1489,599.00,2018-01-23 09:23:30,"Apple iPad Pro 9.7 ""128GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 128GB Wi-Fi Gray Space.,789.0,51871714,190.00,
512,301204,1,APP1492,759.99,2017-01-03 00:17:30,"Apple iPad Pro 9.7 ""128GB Wi-Fi Oro Rosa",New iPad Pro 9.7-inch 128GB Wi-Fi.,789.0,51871714,29.01,
8837,341766,1,APP1501,909.99,2017-04-02 01:34:04,"Apple iPad Pro 9.7 ""Wi-Fi + Cellular 128GB Spa...",9.7-inch Apple iPad Pro Wi-Fi + Cellular 128GB...,939.0,51871714,29.01,
44736,485771,1,APP1489,599.00,2018-01-12 22:50:12,"Apple iPad Pro 9.7 ""128GB Wi-Fi Gray Space",9.7-inch Apple iPad Pro 128GB Wi-Fi Gray Space.,789.0,51871714,190.00,
12241,358320,1,AP20093,529.00,2017-05-23 11:19:20,"Like new - Apple iPad Pro 9.7 ""Wi-Fi 32GB Spac...",9.7-inch iPad Pro Refurbished 32GB Space Gray,679.0,51871714,150.00,
3290,310597,1,APP1490,757.99,2017-01-16 18:27:06,"Apple iPad Pro 9.7 ""128GB Wi-Fi Plata",New iPad Pro 9.7-inch 128GB Wi-Fi.,789.0,51871714,31.01,

In [ ]:
# Function to categorize products
def categorize_product(row, column_name):
    value = row[column_name]  # Extract value from the given column

    categories = {
        11865403: 'Phone Cases/Covers',
        5403: 'Phone & Mac Cases/Covers',
        12175397: 'Server Storage & Data Mgmt',
        1298: 'Open - Accessories & Gadgets',
        11935397: 'Hard Drives',
        1282: 'Macs & Imac',
        12635403: 'Ipad Cases/Covers',
        13835403: 'Macbook Cases/Covers',
        1364: 'Memory (RAM) for Mac Computers',
        12585395: 'Adapters & Hubs',
        1296: 'Monitors',
        1325: 'Cables & Adapters',
        5384: 'Headsets & Headphones',
        1433: 'SSD Expansion Kits',
        12215397: 'SSD Expansion Kits',
        5398: 'Portable Speakers',
        # 1020000000000: 'Apple Macbook Pro (Core i5)',  # Fixed scientific notation
        # 144000000000: 'Repair Service',  # Fixed scientific notation
        57445397: 'Memory Cards & USB Drives',
        1334: 'Wifi Adapter & Accessories',
        11905404: 'Other',
        12655397: 'Hard Drives',
        1230: 'Cables & Adapters',
        1405: 'Wacom Tablets',
        1231: 'Apple Care',
        12175397: 'NAS',
        42945397: 'Hard Drives',
        12755395: 'Hard Drives Accessories',
        13555403: 'Phone Cases/Covers',
        13615399: 'Charger',
        13855401: 'Keyboards',
        10142: 'Batteries',
        51601716: 'IPhone',
        1229: 'Pens & Pointers',
        14305406: 'Tools & Toolkits',
        12995397: 'Hard Drives Accessories',
        13005399: 'Charger',
        12645406: 'Tools & Toolkits',
        12575403: 'Keyboards',
        1515: 'Batteries',
        1387: 'Mouses',
        5395: 'Cables & Adapters',
        8696: 'Stands & Supports',
        1392: 'Backpacks & Bags',
        24895185: 'Apple Watch',
        21561716: 'IPhone',
        21485407: 'Replacement Parts',
        85641716: 'IPhone',
        2449: 'Apple Watch Accessories',
        113291716: 'IPhone',
        24215399: 'Apple Watch Accessories',
        1714: 'IPad',
        14365395: 'Cables & Adapters',
        5720: 'Stands & Supports',
        5399: 'Charger',
        2425: 'Screen protector for Apple Watch',
        113281716: 'Apple Watch Accessories',
        106431714: 'IPad',
        10230: 'Backpacks & Bags',
        85651716: 'IPhone',
        9094: 'Cameras',
        24885185: 'Apple Watch',
        5401: 'Keyboards',
        1282: 'Macs & Imac',
        24821716: 'IPhone',

        1276: 'Cables & Adapters',
        2434: 'Apple Watch Accessories',
        101781405: 'Replacement Parts',
        11821715: 'IPod',
        5405: 'Phone Accessories',
        1216: 'Stands & Supports',
        14035403: 'IPad Covers',
        4259: 'Apple TV',
        51871714: 'IPad'
    }

    return categories.get(value, 'Other')  # Use `.get()` for cleaner lookup

# Apply the function to the dataframe
discounts_df['product_category'] = discounts_df.apply(lambda row: categorize_product(row, 'type'), axis=1)

In [ ]:
discounts_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53231 entries, 0 to 53230
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id_order          53231 non-null  int64
 1   product_quantity  53231 non-null  int64
 2   sku               53231 non-null  object
 3   unit_price        53231 non-null  float64
 4   date              53231 non-null  object
 5   name              53231 non-null  object
 6   desc              53231 non-null  object
 7   price             53231 non-null  float64
 8   type              52904 non-null  Int64
 9   discount          53231 non-null  float64
 10  product_category  53231 non-null  object
dtypes: Int64(1), float64(3), int64(2), object(5)
memory usage: 4.5+ MB

In [ ]:
discounts_df

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount,product_category
0,299545,1,OWC0100,47.49,2017-01-01 01:46:16,OWC In-line Digital Temperature Sensor Kit HDD...,Kit temperature sensor for HDD iMac 21 inch an...,60.99,12755395,13.50,Hard Drives Accessories
1,299546,1,IOT0014,18.99,2017-01-01 01:50:34,iOttie Easy View 2 Car Black Support,IPhone car holder 7 plus / 7/6 Plus / 6 / 5s /...,22.95,5720,3.96,Stands & Supports
2,295347,1,APP0700,72.19,2017-01-01 01:54:11,Apple 85W MagSafe 2 charger MacBook Pro screen...,Apple MagSafe 2 Charger for MacBook Pro 15-inc...,89.00,13005399,16.81,Charger
3,299556,1,CRU0039-A,60.90,2017-01-01 02:20:14,(Open) Crucial 240GB SSD 7mm BX200,SSD hard drive and high-speed performance with...,76.99,1298,16.09,Open - Accessories & Gadgets
4,299561,1,PEB0015,142.49,2017-01-01 02:38:50,Pebble Smartwatch Time Steel Black,Bluetooth Smart Watch with steel case leather ...,299.99,11905404,157.50,Other
...,...,...,...,...,...,...,...,...,...,...,...
53226,527035,1,APP0698,9.99,2018-03-14 11:42:41,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,Cables & Adapters
53227,527070,2,APP0698,9.99,2018-03-14 11:49:01,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,Cables & Adapters
53228,527074,2,APP0698,9.99,2018-03-14 11:49:36,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,Cables & Adapters
53229,527096,3,APP0698,9.99,2018-03-14 11:54:35,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,Cables & Adapters
53230,527112,1,APP0698,9.99,2018-03-14 11:58:13,Apple Lightning Cable Connector to USB 1m Whit...,Apple Lightning USB Cable 1 meter to charge an...,25.00,1230,15.01,Cables & Adapters

In [ ]:
discounts_df[discounts_df.isna().any(axis=1)]

,id_order,product_quantity,sku,unit_price,date,name,desc,price,type,discount,product_category
60,299858,1,LIF0095,94.99,2017-01-01 18:33:34,Lifeproof Fre Power 2600mAh Battery Case Water...,Submersible battery cover with water up to 2 m...,129.99,<NA>,35.00,Other
82,299947,1,APP1482,549.00,2017-01-01 20:32:33,Apple iPhone 64GB Silver,New iPhone SE with 4-inch screen 64 free GB.,549.00,<NA>,0.00,Other
218,300389,1,MOP0073,84.99,2017-01-02 11:13:28,Mophie Juice Pack Air Case Battery (2750 mAh) ...,Case 2750 mAh battery and LED indicator for iP...,109.99,<NA>,25.00,Other
272,300497,1,REP0134,89.99,2017-01-02 12:44:12,Full screen repair iPhone 5,Repair service including parts and labor for i...,59.99,<NA>,-30.00,Other
762,302007,1,APP1188,879.00,2017-01-03 20:37:51,Apple iPhone 6s Plus 128GB Gold,New iPhone 6s Plus 128GB Libre.,749.00,<NA>,-130.00,Other
...,...,...,...,...,...,...,...,...,...,...,...
52344,522282,1,APP2072,969.00,2018-03-06 16:48:25,"Apple MacBook Air 13 ""Core i5 18GHz | 8GB RAM ...",laptop MacBook Air 13 inch i5 18GHz 8GB RAM an...,1105.59,<NA>,136.59,Other
52481,522896,1,APP2072,969.00,2018-03-07 18:13:08,"Apple MacBook Air 13 ""Core i5 18GHz | 8GB RAM ...",laptop MacBook Air 13 inch i5 18GHz 8GB RAM an...,1105.59,<NA>,136.59,Other
52637,523456,1,APP2072,969.00,2018-03-08 20:00:55,"Apple MacBook Air 13 ""Core i5 18GHz | 8GB RAM ...",laptop MacBook Air 13 inch i5 18GHz 8GB RAM an...,1105.59,<NA>,136.59,Other
52982,525830,1,APP2072,969.00,2018-03-12 11:10:01,"Apple MacBook Air 13 ""Core i5 18GHz | 8GB RAM ...",laptop MacBook Air 13 inch i5 18GHz 8GB RAM an...,1105.59,<NA>,136.59,Other
53174,526672,1,APP2072,969.00,2018-03-13 21:32:25,"Apple MacBook Air 13 ""Core i5 18GHz | 8GB RAM ...",laptop MacBook Air 13 inch i5 18GHz 8GB RAM an...,1105.59,<NA>,136.59,Other

In [ ]:
# save discounts_df to categories.csv ask for path
discounts_df.to_csv('categories.csv', index=False)

In [ ]:
from google.colab import files
files.download('categories.csv')